# Generated by Django 5.1.6 on 2025-02-27 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_event_alter_participant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participants.event'),
            preserve_default=False,
        ),
    ]
